name: Challenge 01
on: push
jobs:
    linux:
        runs-on: ubuntu-latest
        steps:
        - name: Display date
          run: date "+%d/%m/%Y"
    windows:
        runs-on: windows-latest
        steps:
        - name: Display date
          run: Get-Date -Format "dd/MM/yyyy"
    macos:
        runs-on: macos-latest
        steps:
        - name: Display date
          run: date "+%d/%m/%Y"
    dependent:
        needs: [linux, windows, macos]
        runs-on: ubuntu-latest
        steps:
        - name: Display date
          run: date "+%d/%m/%Y"