name: Challenge 01
on: push
jobs:
    job01:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v3.2.0
        - name: Display date
          run: date "+%d/%m/%Y"
    job02:
        runs-on: windows-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v3.2.0
        - name: Display date
          run: Get-Date -Format "dd/MM/yyyy"
    job03:
        runs-on: macos-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v3.2.0
        - name: Display date
          run: date "+%d/%m/%Y"
    job04:
        needs: [job01, job02, job03]
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v3.2.0
        - name: Display date
          run: date "+%d/%m/%Y"